<?xml version="1.0" encoding="UTF-8" ?>

<!--
<!DOCTYPE HechosHistoricos [
        <!ELEMENT HechosHistoricos (HechoHistorico)>
        <!ATTLIST HechoHistorico descripcion CDATA #REQUIRED>
        <!ELEMENT HechoHistorico (Fecha)>
        <!ELEMENT Fecha (Dia, Mes, A単o)>
        <!ELEMENT Dia (#PCDATA)>
        <!ELEMENT Mes (#PCDATA)>
        <!ELEMENT A単o (#PCDATA)>
        ]>
        -->
<!DOCTYPE HechosHistoricos SYSTEM "HechosHistoricos.dtd">
<HechosHistoricos>
    <HechoHistorico descripcion="AAAAA">
        <Fecha>
            <Dia></Dia>
            <Mes></Mes>
            <A単o></A単o>
        </Fecha>
        <Epoca/>
    </HechoHistorico>
</HechosHistoricos>